version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "Europe/Vienna" # Ensures the 8:00 AM execution matches your local time
